Info2024/Models/Text.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Info2024.Models
{
	public class Text
	{
		public Text()
		{
			Title = string.Empty;
			Summary = string.Empty;
			Content = string.Empty;
			Keywords = string.Empty;
			Graphic = string.Empty;
			AddedDate = DateTime.Now;
			Active = true;
		}

		public int TextId { get; set; }

		[Required(ErrorMessage = "Tytuł jest wymagany")]
		[Display(Name = "Tytuł tekstu:")]
		[StringLength(75, ErrorMessage = "Tytuł tekstu nie może przekraczać 75 znaków")]
		public string Title { get; set; }

		[Required(ErrorMessage = "Streszczenie jest wymagane")]
		[Display(Name = "Streszczenie tekstu:")]
		[StringLength(255, ErrorMessage = "Streszczenie nie może przekraczać 255 znaków")]
		[DataType(DataType.MultilineText)]
		public string Summary { get; set; }

		[Display(Name = "Słowa kluczowe:")]
		[StringLength(255, ErrorMessage = "Słowa kluczowe nie mogą być dłuższe niż 255 znaków")]
		public string Keywords { get; set; }

		[Required(ErrorMessage = "Treść jest wymagana")]
		[Display(Name = "Treść tekstu:")]
		[DataType(DataType.MultilineText)]
		public string Content { get; set; }

		[Display(Name = "Grafika do tekstu:")]
		[StringLength(128)]
		public string? Graphic { get; set; }

		[Required]
		[Display(Name = "Czy wyświetlać?")]
		public bool Active { get; set; }

		[Required]
		[Display(Name = "Data dodania:")]
		[DataType(DataType.Date, ErrorMessage ="Niepoprawny format daty")]
		[DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
		public DateTime AddedDate { get; set; }

		[Required]
		[Display(Name = "Kategoria tekstu:")]
		public int CategoryId { get; set; }
		//Kategoria tekstu
		[ForeignKey("CategoryId")]
		public Category? Category { get; set; }
		
		[Display(Name = "Autor tekstu:")]
		public string? UserId { get; set; } 
		//Autor tekstu
		[ForeignKey("UserId")]
		public AppUser? Author { get; set; }

		//Lista wszystkich komentarzy dodanych do tekstu
		public ICollection<Opinion> Opinions { get; set; } = new List<Opinion>();
	}
}

Info2024/Controllers/OpinionsController.cs
using Info2024.Data;
using Info2024.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Text = Info2024.Models.Text;

namespace Info2024.Controllers
{
	public class OpinionsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public OpinionsController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Opinions
		[Authorize(Roles="admin")]
		public async Task<IActionResult> Index(int? id)
		{
			if (id == null)
			{
				var allOpinions = _context.Opinions.Include(o => o.Author).Include(o => o.Text);
				return View(await allOpinions.ToListAsync());
			}
			else
			{
				var filteredOpinions = _context.Opinions.Include(o => o.Author).Include(o => o.Text).
					Where(o => o.TextId == id);
				return View(await filteredOpinions.ToListAsync());
			}
		}

		// GET: Opinions/Details/5
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var opinion = await _context.Opinions
					.Include(o => o.Author)
					.Include(o => o.Text)
					.FirstOrDefaultAsync(m => m.OpinionId == id);
			if (opinion == null)
			{
				return NotFound();
			}

			return View(opinion);
		}

		// GET: Opinions/Create
		[Authorize]
		public IActionResult Create(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			Text? text = _context.Texts.Find(id);
			if (text == null) 
			{
				return BadRequest();
			}

			var opinion = new Opinion
			{
				UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
				TextId = text.TextId
			};

			ViewData["TextTitle"] = text.Title;

			return View(opinion);
		}

		// POST: Opinions/Create
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("OpinionId,Comment,Rating,TextId,UserId")] Opinion opinion)
		{
			if (ModelState.IsValid)
			{
				opinion.AddedDate = DateTime.Now;
				_context.Add(opinion);
				await _context.SaveChangesAsync();
				return RedirectToAction("Details", "Texts", new { id = opinion.TextId }, "comments");
			}
			opinion.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			ViewData["TextTitle"] = opinion.Text?.Title;
			return View(opinion);
		}

		// POST: Opinions/CreatePartial
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreatePartial([Bind("OpinionId,Comment,Rating,TextId,UserId")] Opinion opinion)
		{
			if (ModelState.IsValid)
			{
				opinion.AddedDate = DateTime.Now;
				_context.Add(opinion);
				await _context.SaveChangesAsync();
				return RedirectToAction("Details", "Texts", new { id = opinion.TextId }, "comments");
			}
			opinion.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			ViewData["TextTitle"] = opinion.Text?.Title;
			return RedirectToAction("Details", "Texts", new { id = opinion.TextId }, "comments");
		}

		// GET: Opinions/Edit/5
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var opinion = await _context.Opinions.FindAsync(id);
			if (opinion == null)
			{
				return NotFound();
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", opinion.UserId);
			ViewData["TextId"] = new SelectList(_context.Texts, "TextId", "Content", opinion.TextId);
			return View(opinion);
		}

		// POST: Opinions/Edit/5
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("OpinionId,Comment,AddedDate,Rating,TextId,UserId")] Opinion opinion)
		{
			if (id != opinion.OpinionId)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(opinion);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OpinionExists(opinion.OpinionId))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", opinion.UserId);
			ViewData["TextId"] = new SelectList(_context.Texts, "TextId", "Content", opinion.TextId);
			return View(opinion);
		}

		// GET: Opinions/Delete/5
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var opinion = await _context.Opinions
					.Include(o => o.Author)
					.Include(o => o.Text)
					.FirstOrDefaultAsync(m => m.OpinionId == id);
			if (opinion == null)
			{
				return NotFound();
			}

			return View(opinion);
		}

		// POST: Opinions/Delete/5
		[Authorize(Roles = "admin")]
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var opinion = await _context.Opinions.FindAsync(id);
			if (opinion != null)
			{
				_context.Opinions.Remove(opinion);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool OpinionExists(int id)
		{
			return _context.Opinions.Any(e => e.OpinionId == id);
		}
	}
}

Info2024/Controllers/TextsController.cs
using Info2024.Data;
using Info2024.Infrastructure;
using Info2024.Models;
using Info2024.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;


namespace Info2024.Controllers
{
	public class TextsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private IWebHostEnvironment _hostEnvironment;

		public TextsController(ApplicationDbContext context, IWebHostEnvironment environment)
		{
			_context = context;
			_hostEnvironment = environment;
		}

		// GET: Texts
		public async Task<IActionResult> Index(string Fraza, string Autor, int? Kategoria, string Klucz, int PageNumber = 1)
		{
			TextIndexViewModel textIndexViewModel = new()
			{
				TextList = new()
			};

			var SelectedTexts = _context.Texts?
								 .Include(t => t.Category)
								 .Include(t => t.Author)
								 .Where(t => t.Active == true)
								 .OrderByDescending(t => t.AddedDate);

			if (Kategoria != null)
			{
				SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Category.CategoryId == Kategoria);
			}
			if (!String.IsNullOrEmpty(Autor))
			{
				SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Author.Id == Autor);
			}
			if (!String.IsNullOrEmpty(Fraza))
			{
				SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Content.Contains(Fraza));
			}
			if (!String.IsNullOrEmpty(Klucz))
			{
				SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Keywords.Contains(Klucz));
			}

			textIndexViewModel.TextList.TextCount = SelectedTexts.Count();

			textIndexViewModel.TextList.PageNumber = PageNumber;

			textIndexViewModel.TextList.Author = Autor;
			textIndexViewModel.TextList.Phrase = Fraza;
			textIndexViewModel.TextList.Category = Kategoria;
			textIndexViewModel.TextList.Keyword = Klucz;

			textIndexViewModel.Texts = await SelectedTexts
								.Skip((PageNumber - 1) * textIndexViewModel.TextList.PageSize)
								.Take(textIndexViewModel.TextList.PageSize)
								.ToListAsync();

			ViewData["Category"] = new SelectList(_context.Categories
				.Where(c => c.Active == true)
				.OrderBy(c => c.Name),
				"CategoryId", "Name", Kategoria);

			ViewData["Author"] = new SelectList(_context.Texts
				.Include(u => u.Author)
				.Select(u => u.Author)
				.Distinct(),
				"Id", "FullName", Autor);

			var tags = _context.Texts
				.AsEnumerable() 
				.Where(t => !string.IsNullOrEmpty(t.Keywords))
				.SelectMany(t => t.Keywords.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
				.Select(k => k.Trim())
				.Distinct(StringComparer.OrdinalIgnoreCase)
				.OrderBy(k => k)
				.ToList();

			ViewData["Keyword"] = tags;

			return View(textIndexViewModel);
		}

		// GET: Texts List
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> List()
		{
			var applicationDbContext = _context.Texts.Include(t => t.Author).Include(t => t.Category);
			return View(await applicationDbContext.ToListAsync());
		}


		// GET: Texts/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound	();
			}

			var selectedText = await _context.Texts
					.Include(t => t.Category)
					.Include(t => t.Author)
					.Include(t => t.Opinions)
					.ThenInclude(c => c.Author)
					.Where(t => t.Active == true && t.TextId == id)
					.FirstOrDefaultAsync();
			
			if (selectedText == null)
			{
				return NotFound();
			}

			TextWithOpinions textWithOpinions = new()
			{
				SelectedText = selectedText,
				ReadingTime = (int)Math.Ceiling((double) selectedText.Content.Length / 1400),
				CommentsCount = selectedText.Opinions.Count,
				NewOpinion = new()
				{
					TextId = selectedText.TextId,
					UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
			    Text = selectedText
				}
			};

			textWithOpinions.RatingsCount = textWithOpinions.CommentsCount > 0
				? selectedText.Opinions.Count(x => x.Rating != null) : 0;

			textWithOpinions.AverageRating = textWithOpinions.RatingsCount > 0
			? (float)selectedText.Opinions.Where(x => x.Rating != null).Average(x => (int)x.Rating)
			: 0f;

			textWithOpinions.Description = Variety.Phrase("komentarz", "komentarze", "komentarzy", textWithOpinions.CommentsCount);

			return View(textWithOpinions);
		}

		// GET: Texts/Create
		[Authorize(Roles = "admin, author")]
		public IActionResult Create()
		{
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
			return View();
		}

		// POST: Texts/Create
		[Authorize(Roles = "admin, author")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("TextId,Title,Summary,Keywords,Content,Active,CategoryId")] Text text, IFormFile? picture)
		{
			if (ModelState.IsValid)
			{
				if (picture != null && picture.Length > 0)
				{
					var allowedTypes = new[] { "image/jpeg", "image/png", "image/gif", "image/webp" };
					if (!allowedTypes.Contains(picture.ContentType))
					{
						ModelState.AddModelError("Graphic", "Niedozwolony typ pliku");
						ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
						return View(text);
					} 
					else 
					{ 
						ImageFileUpload imageFileResult = new(_hostEnvironment);
						FileSendResult fileSendResult = imageFileResult.SendFile(picture, "img", 600);
						if (fileSendResult.Success)
						{
							text.Graphic = fileSendResult.Name;
						}
						else
						{
							ModelState.AddModelError("Graphic", fileSendResult.Error);
							ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
							return View(text);
						}
					}
				}
				text.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
				text.AddedDate = DateTime.Now;
				_context.Add(text);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
			return View(text);
		}

		// GET: Texts/Edit/5
		[Authorize(Roles = "admin, author")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var text = await _context.Texts.FindAsync(id);
			if (text == null)
			{
				return NotFound();
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", text.UserId);
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Description", text.CategoryId);
			return View(text);
		}

		// POST: Texts/Edit/5
		[Authorize(Roles = "admin, author")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("TextId,Title,Summary,Keywords,Content,Graphic,Active,AddedDate,CategoryId,UserId")] Text text)
		{
			if (id != text.TextId)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(text);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!TextExists(text.TextId))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", text.UserId);
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Description", text.CategoryId);
			return View(text);
		}

		// GET: Texts/Delete/5
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var text = await _context.Texts
					.Include(t => t.Author)
					.Include(t => t.Category)
					.FirstOrDefaultAsync(m => m.TextId == id);
			if (text == null)
			{
				return NotFound();
			}

			return View(text);
		}

		// POST: Texts/Delete/5
		[Authorize(Roles = "admin")]
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var text = await _context.Texts.FindAsync(id);
			if (text != null)
			{
				_context.Texts.Remove(text);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool TextExists(int id)
		{
			return _context.Texts.Any(e => e.TextId == id);
		}
	}
}

Info2024/Views/Texts/Create.cshtml
@model Info2024.Models.Text

@{
	ViewData["Title"] = "Dodawanie tekstu";
}

<h1 class="text-primary">Dodawanie tekstu</h1>

<h4 class="text-success">Nowy tekst</h4>
<hr />
<div class="row">
	<div class="col-md-8 interspace">
		<form asp-action="Create" enctype="multipart/form-data">
			<input type="hidden" id="UserId" name="UserId" value="@ViewData["UserId"]" />
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Summary" class="control-label"></label>
				<textarea asp-for="Summary" class="form-control"></textarea>
				<span asp-validation-for="Summary" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Keywords" class="control-label"></label>
				<input asp-for="Keywords" class="form-control" />
				<span asp-validation-for="Keywords" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Content" class="control-label"></label>
				<textarea id="editor" asp-for="Content" class="form-control"></textarea>
				<span asp-validation-for="Content" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Graphic" class="control-label"></label>
				<input type="file" name="picture" id="picture" class="form-control" accept=".jpg,.gif,.png,.webp" />
				<span asp-validation-for="Graphic" class="text-danger"></span>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
				</label>
			</div>
			<div class="form-group">
				<label asp-for="CategoryId" class="control-label"></label>
				<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
					<option value="">--- Wybierz kategorię ---</option>
				</select>
			</div>
			<div class="form-group">
				<input type="submit" value="Dodaj tekst" class="btn btn-primary" />
				<a asp-action="Index" class="btn btn-light">Powrót do listy</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script src="~/lib/ckeditor5/ckeditor.min.js"></script>
	<script src="~/lib/ckeditor5/translations/pl.min.js"></script>
	<script>
		ClassicEditor
				.create(document.querySelector('#editor'), {
						language: 'pl'
				})
				.catch(error => {
						console.error(error);
				});
	</script>
}

Info2024/Views/Texts/Delete.cshtml
@model Info2024.Models.Text

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Text</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Keywords)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Graphic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Graphic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TextId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Info2024/Views/Texts/List.cshtml
@model IEnumerable<Info2024.Models.Text>

@{
	ViewData["Title"] = "Lista tekstów";
}

<h1 class="text-primary">Teksty</h1>

<table class="table" id="teksty">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Summary)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Keywords)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Content)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Graphic)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Active)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.AddedDate)
			</th>
			<th>
				Kategoria:
			</th>
			<th>
				Autor:
			</th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Title)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Summary)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Keywords)
				</td>
				<td>
					@if (item.Content.Length <= 75)
					{
						@Html.DisplayFor(modelItem => item.Content)
					}
					else
					{
						@(item.Content.Substring(0, 75) + "...")
					}
				</td>
				<td>
					<img src="@Url.Content(String.IsNullOrEmpty(item.Graphic) ? "~/img/mini/brak.jpg" : "~/img/mini/"+item.Graphic)" width="150" alt="@item.Category.Name" />
				</td>
				<td>
					@(item.Active == true ? "Tak" : "Nie")
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AddedDate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Category.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Author.FullName)
				</td>
				<td>
					<a class="btn btn-outline-primary rounded-circle my-1" title="Szczegóły" asp-action="Details" asp-route-id="@item.TextId"><i class="bi-eye" aria-label="Treść tekstu"></i></a>
					<a class="btn btn-outline-info rounded-circle my-1" title="Opinie" asp-controller="Opinions" asp-action="Index" asp-route-id="@item.TextId"><i class="bi-chat-left-text" aria-label="Opinie o tekście"></i></a>
					<a class="btn btn-outline-warning rounded-circle my-1" title="Edycja" asp-action="Edit" asp-route-id="@item.TextId"><i class="bi-pen-fill" aria-label="Edycja tekstu"></i></a>
					<a class="btn btn-outline-danger rounded-circle my-1" title="Usuwanie" asp-action="Delete" asp-route-id="@item.TextId"><i class="bi-trash" aria-label="Usuwanie tekstu"></i></a>
				</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</tfoot>
</table>

@section Scripts {
	<script src="https://cdn.datatables.net/v/bs5/dt-2.1.8/datatables.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#teksty').DataTable({
				language: {
					"decimal": "",
					"emptyTable": "Brak danych do wyświetlenia",
					"info": "Pozycje od _START_ do _END_ z _TOTAL_ rekordów",
					"infoEmpty": "Pozycji 0 z 0 dostępnych",
					"infoFiltered": "(filtrowanie z _MAX_ dostępnych pozycji)",
					"infoPostFix": "",
					"thousands": " ",
					"lengthMenu": "Pokaż _MENU_ pozycji",
					"loadingRecords": "Ładowanie...",
					"processing": "Przetwarzanie...",
					"search": "Wyszukaj:",
					"zeroRecords": "Nie znaleziono danych",
					"paginate": {
							"first": "Pierwsza",
							"last": "Ostatnia",
							"next": "Następna",
							"previous": "Poprzednia"
					},
					"aria": {
							"sortAscending": ": sortuje kolumnę rosnąco",
							"sortDescending": ": sortuje kolumnę malejąco"
					}
			},
				initComplete: function () {
					this.api().columns().every(function () {
							var column = this;
							var header = $(column.header()).text().trim();
							// Pomijanie kolumny z grafiką
							if (header === 'Grafika do tekstu:') {
									return;
							}
							// Standardowe pole tekstowe dla pozostałych kolumn
							var select = $('<input type="text" class="form-control"/>')
							.attr('placeholder', header)
							.appendTo($(column.footer()).empty())
							.on('keyup change clear', function () {
									if (column.search() !== this.value) {
											column.search(this.value).draw();
									}
							});
					});
				}
			});
		});
	</script>
}